#!/usr/bin/env bash
# Generates the simnet build from the deployable contract.
#
# at-stake.clar targets MAINNET, which is where it deploys:
#   sBTC  SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token
#   pox-5 SP000000000000000000002Q6VF78.pox-5
#
# One substitution: pox-5 -> pox5-sim, the SAME contract generated by
# build-pox5-sim.sh but under our address so tests hold bond-admin. Not a mock.
#
# The header bypass is no longer here. at-stake delegates the header check to
# pox-5's verify-block-header, so SIM-SKIP-HEADER lives only in pox5-sim now.
#
# contracts/at-stake-sim.clar is generated. Never edit it, never deploy it.
set -e
sed -e "s|'SP000000000000000000002Q6VF78.pox-5|'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.pox5-sim|g" \
  contracts/at-stake.clar > contracts/at-stake-sim.clar
cat >> contracts/at-stake-sim.clar <<'SIM'

;; ===== SIMNET ONLY. Not present in the deployed contract. =====
(define-public (test-seed-market (id uint) (title (string-ascii 64))
                                 (subject-script (buff 34)) (bond-index uint)
                                 (close-height uint)
                                 (created-at uint) (threshold-sats uint) (snapshot-sats uint))
  (begin
    (map-set markets { id: id }
      { title: title, subject-script: subject-script, bond-index: bond-index,
        close-height: close-height,
        created-at: created-at, threshold-sats: threshold-sats,
        snapshot-sats: snapshot-sats, status: STATUS_OPEN,
        vault: u0, idle-circ: u0, bonded-circ: u0 })
    (ok true)))

(define-read-only (test-tx-output (tx (buff 16384)) (index uint))
  (get-bitcoin-tx-output? tx index))

(define-read-only (test-merkle (txid (buff 32)) (root (buff 32)) (idx uint)
                              (count uint) (hashes (list 14 (buff 32))))
  (verify-merkle-proof txid root idx count hashes))

(define-public (test-set-bonded (id uint))
  (let ((m (unwrap! (map-get? markets { id: id }) ERR_NO_MARKET)))
    (map-set markets { id: id } (merge m { status: STATUS_BONDED }))
    (ok true)))
SIM
echo "built contracts/at-stake-sim.clar"
